application: friend-online
version: 3
runtime: php
api_version: 1

handlers:
 
- url: /(.*\.(js|css))$
  static_files: assets/\1
  upload: assets/.*\.(js|css)$
  secure: always  

- url: /(.*\.(png))$
  static_files: assets/\1
  upload: assets/.*\.(png)$
  application_readable: true
  
- url: /static/(.+)
  script: assets/static/\1
  secure: always
  
- url: /header.php
  script: assets/static/header.php
  secure: always
  
- url: /foot.php
  script: assets/static/foot.php
  secure: always

- url: /(.+)?/?
  script: assets/RunApp.php
  secure: always
