application: perfect-crawler-517
version: 4
runtime: php
api_version: 1

handlers:
 
- url: /(.*\.(js|css))$
  static_files: assets/\1
  upload: assets/.*\.(js|css)$
  secure: always  

- url: /(.*\.(ico|jpg|png|gif))$
  static_files: assets/\1
  upload: assets/.*\.(ico|jpg|png|gif)$
  application_readable: true
  
- url: /(.+)
  script: assets/\1
  secure: always
  
- url: /header.php
  script: assets/header.php
  secure: always
  
- url: /foot.php
  script: assets/foot.php
  secure: always

- url: /robots.txt
  static_files: assets/robots.txt
  upload: assets/robots.txt 
  secure: always  

- url: /(.+)?/?
  script: assets/RunApp.php
